---
- name: RackHD Demonstration Server
  hosts: local
  sudo: no
  roles:
    - apt
    - build
    - git
    - rabbitmq
    - mongodb
    - node
    - isc-dhcp-server
    - monorail
    - snmptool
    - ipmitool
    - integrationtest
    - postgresql
    - setuptools
    - rackhd-release
