---
- name: RackHD Demonstration Server
  hosts: local
  vars:
    rackhd_version: ""
    is_release: false
  sudo: no
  roles:
    - apt
    - build
    - git
    - rabbitmq
    - mongodb
    - node
    - isc-dhcp-server
    - monorail
    - snmptool
    - ipmitool
    - integrationtest
    - postgresql
    - setuptools
    - rackhd-builds
