# Copyright 2016, EMC, Inc.

version: '2'

services:

  mongo:
    image: mongo:latest
    network_mode: "host"
    ports:
      - "27017:27017"
    privileged: true

  rabbitmq: # 5672, 15672
    image: rabbitmq:management
    network_mode: "host"
    privileged: true

  dhcp: # 67/udp
    image: rackhd/isc-dhcp-server
    build: "./dhcp"
    network_mode: "host"
    privileged: true
    volumes:
      - "./dhcp/leases:/var/lib/dhcp"
      - "./dhcp/config:/etc/dhcp"
      - "./dhcp/defaults:/etc/defaults"

  files:
    build: "./files"
    image: "rackhd/files"
    network_mode: "host"
    privileged: true
    volumes:
      - "./files/mount:/RackHD/files"

  # RackHD services

  core:
    build: "../on-core"
    image: rackhd/on-core:latest
    command: "/bin/echo exit"

  dhcp-proxy: # 68/udp, 4011
    build: "../on-dhcp-proxy"
    depends_on:
      - dhcp
      - logstash
      - mongo
      - rabbitmq
      - statsd
    image: rackhd/on-dhcp-proxy:latest
    network_mode: "host"
    privileged: true
    volumes:
      - "./monorail:/opt/monorail"

  http: # 9090, 9080
    build: "../on-http"
    depends_on:
      - files
      - logstash
      - mongo
      - rabbitmq
      - statsd
    image: rackhd/on-http:latest
    network_mode: "host"
    privileged: true
    volumes:
      - "./files/mount/common:/RackHD/on-http/static/http/common"
      - "./monorail:/opt/monorail"

  statsd: # 8125/udp
    build: "../on-statsd"
    depends_on:
      - elasticsearch
      - logstash
      - mongo
      - rabbitmq
    image: rackhd/on-statsd:latest
    network_mode: "host"
    privileged: true
    volumes:
      - "./monorail:/opt/monorail"

  syslog: # 514/udp
    build: "../on-syslog"
    depends_on:
      - mongo
      - logstash
      - rabbitmq
      - statsd
    image: rackhd/on-syslog:latest
    network_mode: "host"
    privileged: true
    volumes:
      - "./monorail:/opt/monorail"

  taskgraph:
    build: "../on-taskgraph"
    depends_on:
      - dhcp
      - logstash
      - mongo
      - rabbitmq
      - syslog
      - statsd
    image: rackhd/on-taskgraph:latest
    network_mode: "host"
    privileged: true
    volumes:
      - "./dhcp/leases:/var/lib/dhcp"
      - "./monorail:/opt/monorail"

  tftp: # 69/udp
    build: "../on-tftp"
    depends_on:
      - files
      - logstash
      - mongo
      - rabbitmq
      - statsd
      - syslog
    image: rackhd/on-tftp:latest
    network_mode: "host"
    privileged: true
    volumes:
      - "./files/mount:/RackHD/on-tftp/static/tftp"
      - "./monorail:/opt/monorail"

  # ELK services

  elasticsearch: # 9200, 9300
    command: elasticsearch -Des.network.host=0.0.0.0
    depends_on:
      - rabbitmq
    image: elasticsearch:latest
    network_mode: "host"
    privileged: true

  logstash: # 5000
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    depends_on:
      - elasticsearch
      - rabbitmq
    image: logstash:latest
    network_mode: "host"
    privileged: true
    volumes:
      - "./logstash/config:/etc/logstash/conf.d"

  kibana: # 5601
    depends_on:
      - elasticsearch
    image: kibana:latest
    network_mode: "host"
    privileged: true
    volumes:
      - "./kibana/config:/opt/kibana/config"
