---
# vagrant ansible uses 1.5, which doesn't have the keyserver option enabled
- shell: "apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 379CE192D401AB61"
  sudo: yes

# apt_repository apparently requires this to run in Ansible 1.5
- apt: pkg=python-pycurl state=present
  sudo: yes

# example: deb https://dl.bintray.com/rackhd/debian trusty release
- apt_repository: repo={{ deb_repository  }}
                  state=present
  sudo: yes


- name: Install RackHD Packages latest
  include: aptitude_install_rackhd.yml
  vars:
    package: rackhd
  sudo: yes
  when: (rackhd_version is undefined) or (not rackhd_version)

- name: Install RackHD Packages specific version
  include: aptitude_install_rackhd.yml
  vars:
    package: rackhd={{ rackhd_version }}
  sudo: yes
  when: (rackhd_version is not undefined) and rackhd_version

- name: Check Installed RackHD version
  shell: |
    installed_version=`apt-cache policy rackhd | grep Installed | awk '{print $2}'`
    echo "[Debug] installed_version=$installed_version"
    if [ "$installed_version" != "{{ rackhd_version }}" ]; then
      echo "Installed wrong rackhd version $installed_version"
      exit 1
    fi
  when: (rackhd_version is not undefined) and rackhd_version
