---
- name: create dir /home/vagrant/src/on-tftp/static/tftp
  file: path=/home/vagrant/src/on-tftp/static/tftp state=directory

- name: download binary support files to /home/vagrant/src/on-tftp/static/tftp
 # get_url:
  #  url: https://dl.bintray.com/rackhd/binary/ipxe/{{item}}
   # dest: ~/src/on-tftp/static/tftp
  shell: wget https://dl.bintray.com/rackhd/binary/ipxe/{{item}}
  with_items:
    - monorail.ipxe
    - monorail-undionly.kpxe
    - monorail-efi64-snponly.efi
    - monorail-efi32-snponly.efi
    - monorail.intel.ipxe
  args:
   chdir: /home/vagrant/src/on-tftp/static/tftp

- name: creare dir /home/vagrant/src/on-http/static/http/common
  file: path=/home/vagrant/src/on-http/static/http/common state=directory

- name: download binary support files to  /home/vagrant/src/on-http/static/http/common
  #get_url:
   # url: https://dl.bintray.com/rackhd/binary/builds/{{item}}
   # dest: ~/src/on-http/static/http/common
  shell: wget https://dl.bintray.com/rackhd/binary/builds/{{item}}
  with_items:
    - base.trusty.3.16.0-25-generic.squashfs.img
    - discovery.overlay.cpio.gz
    - initrd.img-3.16.0-25-generic
    - vmlinuz-3.16.0-25-generic
  args:
    chdir: /home/vagrant/src/on-http/static/http/common
